apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/lgypro/spring-boot-hello-world:v1
        name: spring-boot-hello-world
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 2000Mi
        env:
        - name: JAVA_OPTS
          value: "-javaagent:./agent/jmx_prometheus_javaagent-0.19.0.jar=12345:./agent/config.yaml"
      imagePullSecrets:
      - name: my-secret